<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components [
<!ELEMENT components (component+)>
<!ELEMENT component (type, model)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT model (#PCDATA)>
]>
<components>
  <component>
    <type>Processor</type>
    <model>AMD Ryzen™ 7 5800H</model>
  </component>
  <component>
    <type>RAM</type>
    <model>16 GB DDR4-3200 MHz</model>
  </component>
  <component>
    <type>Storage</type>
    <model>512 GB SSD PCIe® NVMe™ TLC M.2</model>
  </component>
  <component>
    <type>Screen</type>
    <model>40,9 cm (16,1"),(1920 x 1080)</model>
  </component>
  <component>
    <type>Webcam</type>
    <model>HP Wide Vision 720p HD</model>
  </component>
  <component>
    <type>Touchpad</type>
    <model>HP Imagepad</model>
  </component>
</components>
